appCrud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('saludo', include('app.urls')),
    path('addCarrera', include('app.urls')),
    path('agregarCarrera', include('app.urls')),
    path('listar_carreras', include('app.urls')),
    path('editar_carrera/<int:carrera_id>', include('app.urls')),
    path('listar_carreras_full', include('app.urls')),
    path('borrar_carrera/<int:carrera_id>', include('app.urls')),
]

apps/usuario/urls.py
from django.conf.urls import url
from . import views
app_name = 'usuario'


urlpatterns = [
    url('registrar/', views.registrar, name= 'registrar'),
    url('login/', views.usuario_login, name= 'login'),
    url('logout/', views.usuario_logout, name= 'logout'),
    url('', views.index, name= 'index'),
]

tiendaVirtual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('apps.producto.urls')),
    path('listar/', include('apps.producto.urls')),
    path('', include('apps.usuario.urls')),
    path('homepage/', include('apps.producto.urls')),  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" >
    {% block head %}
     {% endblock %}
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Ejemplo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarAccesos" 
        aria-controls="navbarAccesos" aria-expanded="false" aria-label="Toggle navegation">
          <span clas="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarAccesos">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'usuario:index' %}">index</a></li>
            {% if not request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'usuario:login' %}">iniciar sesion</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'usuario:registrar' %}">registrar</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'usuario:logout' %}">logout</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>

    <div class="container">
      {% block content %} 
      {% endblock %}
    </div>
  </body>
</html>